version: '3'

services:
  # db:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=djangoblog
  #     - MYSQL_ROOT_PASSWORD=DjAnGoBlOg!2!Q@W#E
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./bin/datas/mysql/:/var/lib/mysql
  #   depends_on:
  #     - redis
  #   container_name: db

  djangoblog:
    image: djangoblog:250120
    restart: always
    volumes:
      - ./collectedstatic:/code/djangoblog/collectedstatic
      - ./logs:/code/djangoblog/logs
      - ./uploads:/code/djangoblog/uploads
    environment:
      - DJANGO_MYSQL_DATABASE=djangoblog
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=password        ## substitute it with external db password
      - DJANGO_MYSQL_HOST=192.168.244.33           ## subsitute it with external db host 
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_REDIS_URL=redis:6379        
    links:
      - redis
    depends_on:
      - redis
    container_name: djangoblog
    networks:
      - my_network
    ports:
      - "8000:8000"

  nginx:
    restart: always
    image: nginx:latest        ##
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./collectedstatic:/code/djangoblog/collectedstatic
    links:
      - djangoblog:djangoblog
    container_name: nginx
    networks:
      - my_network     ##

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    networks:
      - my_network    ## 


## add a new bridge network shared by djangoblog ,nginx and redis 
networks:
  my_network:
    driver: bridge

