apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: djangoblog
  name: djangoblog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: djangoblog
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: djangoblog
    spec:
      containers:
        - image: djangoblog:250120   # replace it with your own image registry and tag
          imagePullPolicy: IfNotPresent
          name: djangoblog
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /code/djangoblog/logs
              name: djangoblog-pvc
              subPath: logs
            - mountPath: /code/djangoblog/uploads
              name: djangoblog-pvc
              subPath: uploads
            - mountPath: /code/djangoblog/collectedstatic
              name: djangoblog-pvc
              subPath: static
          envFrom:
           - secretRef:
               name: djangoblog-secret
      imagePullSecrets:
            - name: default   # replace it with your own imagePullSecrets
      restartPolicy: Always
      volumes:
        - name: djangoblog-pvc
          persistentVolumeClaim:
            claimName: djangoblog-pvc
