apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate  ##  recreate or rollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:stable   # use a stable version
          name: nginx
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-cm0
              subPath: nginx.conf
            - mountPath: /djangoblog/static    # the path is defined  in nginx.conf, which is wrapped in nginx-configmap
              name: statics
              subPath: static  # same with the subPath defined in volumeMounts part in djangoblog-deployment.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-cm0
          name: nginx-cm0
        - name: statics
          persistentVolumeClaim:
            claimName: djangoblog-pvc   # use the same pvc as djangoblog ,so that the static files can be shared
      
