apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    io.kompose.service: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort            # use NodePort only in non-production environment
