apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: djangoblog-claim2
  name: djangoblog-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi  # use your storage class name
  resources:
    requests:
      storage: 5G 
